<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Sergio Negro Oliva
Curso: 1ºDAM
Fecha: 30/03/2025 
Ejercicio 7: Corrección de errores en XML 
-->

<!DOCTYPE musicos [
    <!ELEMENT musicos (musico*)>
    <!ELEMENT musico (nombre, apodo?, fechaNacimiento)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apodo (#PCDATA)>
    <!ELEMENT fechaNacimiento (#PCDATA)>
]>

<musicos>
    <musico>
        <nombre>Antonio Vivaldi</nombre>
        <apodo>El cura pelirrojo</apodo>
        <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
    </musico>
    <musico>
        <nombre>Johann Sebastian Bach</nombre>
        <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
    </musico>
</musicos>